[package]
name = "portal-solutions-extism-compat"
version = "0.0.1"
edition = "2024"
license = "MPL-2.0"
description = "Extism compatibility for Portal apps"

[dependencies]
base64 = "0.22.1"
extism-pdk = "1.4.1"
